language: python
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
python:
  - "3.5"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install python-wxgtk3.0
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-installer.txt
  - pip install -e . | cat
# command to run tests
script: pyinstaller -y gui/Excel2ldrGui.spec
  
