language: python
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
python:
  - "2.7"
  - "3.5"
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq  python-wxgtk3.0
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-installer.txt
  - pip install -e . | cat
# command to run tests
script: pyinstaller -y gui/Excel2ldrGui.spec
  
