language: python
sudo: false
cache:
  - apt
  - directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
python:
  - "3.6"
addons:
  apt:
     packages:
        - python-wxgtk2.8
virtualenv:
  system_site_packages: true
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-installer.txt
  - pip install -e . | cat
# command to run tests
script: pyinstaller -y gui/Excel2ldrGui.spec
  
