language: python
sudo: false
cache:
  - apt
  - directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
python:
  - "3.4"
virtualenv:
  system_site_packages: true
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e . | cat
# command to run tests
script: pytest
  
